# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*'] # On affinera avec l'URL Vercel plus tard
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['Content-Disposition']
        max_age: 3600
    paths:
        '^/api/': # Assurez-vous que vos routes API commencent par /api
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['*']
            max_age: 3600